/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.TableUI;
import javax.swing.table.DefaultTableCellRenderer;
import modelos.Credito;
import modelos.Cuota;

/**
 *
 * @author Your Name <your.name at your.org>
 */
public class PagoCuotas extends javax.swing.JFrame {


    
    public class TablaCellRedender extends DefaultTableCellRenderer{
        private Component componente;
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
           componente = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
            
           if(isSelected){
                
               componente.setBackground(Color.black);
                
                
          
               componente.setForeground(Color.white);
            }else{
               
               componente.setBackground(Color.white);
                
                
          
               componente.setForeground(Color.black);
                
            }
            return componente;
        }
        
    }
    
    
    
    public PagoCuotas() {
        initComponents();
        radioSeleccionCuotas.setSelected(true);
        tablaCuotas.setDefaultRenderer(Object.class, new TablaCellRedender());
    
    }
    
    
   
    public void iniciar(){

          setVisible(true);
          setLocationRelativeTo(this);
          setTitle("Pago de Cuotas");
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuotas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        radioSeleccionCuotas = new javax.swing.JRadioButton();
        radioPagoMonto = new javax.swing.JRadioButton();
        monto_enviado = new javax.swing.JTextField();
        label_monto = new javax.swing.JLabel();
        boton_confirmar_pago = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(153, 175, 105));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SELECCIONE EL TIPO DE PAGO");

        tablaCuotas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColumnIndex){
                return false;
            }
        };
        tablaCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCuotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCuotas);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("CTRL + CLICK IZQUIERDO    PARA AGREGAR MAS A LA SELECCION");

        radioSeleccionCuotas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        radioSeleccionCuotas.setText("Seleccion de Cuotas");
        radioSeleccionCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSeleccionCuotasActionPerformed(evt);
            }
        });

        radioPagoMonto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        radioPagoMonto.setText("Pago Monto");
        radioPagoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPagoMontoActionPerformed(evt);
            }
        });

        monto_enviado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        label_monto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_monto.setText("INGRESE MONTO:");

        boton_confirmar_pago.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_confirmar_pago.setText("Confirmar Pago");

        boton_cancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_cancelar.setText("Cancelar");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSeleccionCuotas)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioPagoMonto)
                                .addGap(101, 101, 101)
                                .addComponent(label_monto))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(boton_confirmar_pago)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monto_enviado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPagoMonto)
                    .addComponent(monto_enviado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_monto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioSeleccionCuotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_confirmar_pago)
                    .addComponent(boton_cancelar))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCuotasMouseClicked
           
       
    }//GEN-LAST:event_tablaCuotasMouseClicked

    private void radioSeleccionCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSeleccionCuotasActionPerformed
       
            radioSeleccionCuotas.setSelected(true);
            radioPagoMonto.setSelected(false);
            tablaCuotas.setEnabled(true);
            monto_enviado.setVisible(false);
        label_monto.setVisible(false);
        monto_enviado.setText("");
     
     
        
    
    }//GEN-LAST:event_radioSeleccionCuotasActionPerformed

    private void radioPagoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPagoMontoActionPerformed
   
        radioSeleccionCuotas.setSelected(false);
         radioPagoMonto.setSelected(true);
        tablaCuotas.setEnabled(false);
        tablaCuotas.setForeground(Color.GRAY);
        tablaCuotas.setBackground(Color.GRAY);
        monto_enviado.setVisible(true);
        label_monto.setVisible(true);
     
        
     
    }//GEN-LAST:event_radioPagoMontoActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoCuotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_cancelar;
    public javax.swing.JButton boton_confirmar_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_monto;
    public javax.swing.JTextField monto_enviado;
    public javax.swing.JRadioButton radioPagoMonto;
    public javax.swing.JRadioButton radioSeleccionCuotas;
    public javax.swing.JTable tablaCuotas;
    // End of variables declaration//GEN-END:variables

    public void cargarCreditos(ArrayList<Cuota> todaslascuotas) {

       
        todaslascuotas.forEach((cuota)->{
            System.out.println(cuota.getFecha_vencimiento());
        });
        
                // CARGAMOS EL CREDITO EN LA VISTA
       
        String matriz[][] = new String[todaslascuotas.size()][5];
        String formato = "dd/MM/yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        DecimalFormat formato_dec = new DecimalFormat("#.00");
        
   
        for(int i=0; i<todaslascuotas.size(); i++){
            
            matriz[i][0] = String.valueOf("  "+todaslascuotas.get(i).getNro());
            matriz[i][1] = String.valueOf(sdf.format(todaslascuotas.get(i).getFecha_vencimiento()));
            matriz[i][2] = String.valueOf("$ "+formato_dec.format(todaslascuotas.get(i).getMonto()));
            matriz[i][3] = String.valueOf("$ "+formato_dec.format(todaslascuotas.get(i).getRecargo()));
            matriz[i][4] = String.valueOf(todaslascuotas.get(i).getEstado());
            
            
        }
        tablaCuotas.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{
            "Nº Cuota","Vencimiento", "Importe","Recargo","Estado"
        }));
        
        
        
        
    }


}
