
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioPublicoCredito", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://ds.dyndns.org:9000/ServicioPublicoCredito?wsdl")
public class ServicioPublicoCredito
    extends Service
{

    private final static URL SERVICIOPUBLICOCREDITO_WSDL_LOCATION;
    private final static WebServiceException SERVICIOPUBLICOCREDITO_EXCEPTION;
    private final static QName SERVICIOPUBLICOCREDITO_QNAME = new QName("http://tempuri.org/", "ServicioPublicoCredito");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ds.dyndns.org:9000/ServicioPublicoCredito?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOPUBLICOCREDITO_WSDL_LOCATION = url;
        SERVICIOPUBLICOCREDITO_EXCEPTION = e;
    }

    public ServicioPublicoCredito() {
        super(__getWsdlLocation(), SERVICIOPUBLICOCREDITO_QNAME);
    }

    public ServicioPublicoCredito(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOPUBLICOCREDITO_QNAME, features);
    }

    public ServicioPublicoCredito(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOPUBLICOCREDITO_QNAME);
    }

    public ServicioPublicoCredito(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOPUBLICOCREDITO_QNAME, features);
    }

    public ServicioPublicoCredito(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioPublicoCredito(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServicioPublicoCredito
     */
    @WebEndpoint(name = "SGEBusService")
    public IServicioPublicoCredito getSGEBusService() {
        return super.getPort(new QName("http://tempuri.org/", "SGEBusService"), IServicioPublicoCredito.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServicioPublicoCredito
     */
    @WebEndpoint(name = "SGEBusService")
    public IServicioPublicoCredito getSGEBusService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SGEBusService"), IServicioPublicoCredito.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOPUBLICOCREDITO_EXCEPTION!= null) {
            throw SERVICIOPUBLICOCREDITO_EXCEPTION;
        }
        return SERVICIOPUBLICOCREDITO_WSDL_LOCATION;
    }

}
